### ISSUE TITLE
Add @dateValidColumn variable to the pattern template

### ISSUE THREAD

**Issue by ftrojan** [janmotl/PredictorFactory#4]
To support filters and derived fields computations it would be convenient to have @dateValidColumn which denotes the date column in the table which describes the time validity of the record. There can be only zero or one @dateValidColumn for a table, so which one to select if there is more than one @dateColumn? Reasonable statement is that it is the column with the smallest values in each record. The suggested algorithm to find out is to select the column with the highest number of records with the right order:

for (@dateColumn : @allDateColumns)
{
  numOrder = (SELECT 
    AVG(CASE WHEN @dateColumn < @dateValidColumn THEN 1 ELSE 0 END)
    FROM T);
  if (numOrder > numOfRightOrder)
  {
    @dateValidColumn = @dateColumn;
    numOfRightOrder = numOrder;
  }
}

**Comment by janmotl** [comment]
Not all dates should be used as @dateValidColumn. A hypothetical scenario:
1) Customer table with date_birth column
2) We are considering only data, which happen in window: <@dateValidColumn - 1 year, @dateValidColumn>
In this scenario date_birth as @dateValidColumn would result in empty sets. 
How to avoid columns like date_birth in @dateValidColumn? The proposed solution is to look at the size of the set after after filtering with the bounded @dateValidColumn to @dateColumn and compare it with the original size of the set. If, let's say, less than 0.1% of records remain after filtering, the @dateColumn should not be used for @dateValidColumn.

The minimal value appears to be a reasonable heuristic. Currently, a new propagation table is created for each acceptable @dateColumn. And @dateValidColumn is called @propagationDate. If desirable, it can be renamed.

**Comment by janmotl** [comment]
Implemented.
