### ISSUE TITLE
Each predictor should be evaluated in terms of IV and Gini

### ISSUE THREAD

**Issue by ftrojan** [janmotl/PredictorFactory#5]
As tables predictorXXXX are created, we should calculate predictive power of the predictor to the target by issuing SQL statements calculating IV and Gini.

The suggested methodology is to order sample (base table) by the value of predictor, split into N equally sized bins (N possibly determined by Sturge's rule or similar, calculate number of records and number of events (target=1) in each bin by SQL, return the Nx2 matrix back to Java and calculate IV and Gini using standard formulas.

**Comment by janmotl** [comment]
Chi2 was implemented. 

I didn't implement calculation of IV as I do not know how to extend it for multiclass scenarios. Gini will be implemented latter.
